import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyNotice, PageHeader, pretty } from "@/components/CivicPrimitives";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Search, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

export default function AdminUsers() {
  const { user } = useAuth(); const [search, setSearch] = useState(""); const people = trpc.admin.users.useQuery(undefined, { enabled: user?.role === "admin" }); const visible = useMemo(() => (people.data || []).filter(person => `${person.name || ""} ${person.email || ""}`.toLowerCase().includes(search.toLowerCase())), [people.data, search]);
  if (user?.role && user.role !== "admin") return <EmptyNotice title="Administrator access required">This view is reserved for system administration.</EmptyNotice>;
  return <div className="space-y-8"><PageHeader eyebrow="Administrator workspace" title="User directory" description="Review the people registered in the portal and identify staff profiles that can be given an officer assignment." /><section className="surface overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name or email" className="pl-9" /></div></div>{people.isLoading ? <div className="p-6"><div className="h-24 animate-pulse rounded-2xl bg-slate-50" /></div> : visible.length ? <div className="overflow-x-auto"><table className="data-table min-w-[700px]"><thead><tr><th>Person</th><th>Role</th><th>Sign-in method</th><th>Created</th></tr></thead><tbody>{visible.map(person => <tr key={person.id} className="hover:bg-[#fafcfc]"><td><p className="font-semibold text-slate-800">{person.name || "Unnamed account"}</p><p className="mt-1 text-xs text-slate-400">{person.email || "No email shared"}</p></td><td><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${person.role === "admin" ? "bg-[#f9e2e6] text-[#aa6071]" : person.role === "officer" ? "bg-[#dfeffc] text-[#245d8d]" : "bg-slate-100 text-slate-600"}`}>{pretty(person.role)}</span></td><td>{person.loginMethod || "Managed OAuth"}</td><td>{new Date(person.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <div className="p-6"><EmptyNotice title="No people found" icon={<UsersRound className="h-5 w-5" />}>Try another search term once accounts have been created through the managed sign-in service.</EmptyNotice></div>}</section></div>;
}
