import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyNotice, PageHeader, pretty } from "@/components/CivicPrimitives";
import { MutationAlert } from "@/components/MutationAlert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Plus, Tags } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function AdminCategories() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const categories = trpc.admin.categories.useQuery(undefined, { enabled: user?.role === "admin" }); const departments = trpc.admin.departments.useQuery(undefined, { enabled: user?.role === "admin" }); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [departmentId, setDepartmentId] = useState("");
  const create = trpc.admin.createCategory.useMutation({ onSuccess: () => { setName(""); setDescription(""); setDepartmentId(""); utils.admin.categories.invalidate(); utils.public.catalog.invalidate(); toast.success("Category created"); }, onError: error => toast.error(error.message) }); const setStatus = trpc.admin.setCategoryStatus.useMutation({ onSuccess: () => { utils.admin.categories.invalidate(); utils.public.catalog.invalidate(); toast.success("Category status updated"); } });
  if (user?.role && user.role !== "admin") return <EmptyNotice title="Administrator access required">This view is reserved for system administration.</EmptyNotice>;
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ name: name.trim(), departmentId: Number(departmentId), description: description.trim() || undefined }); };
  return <div className="space-y-8"><PageHeader eyebrow="Administrator workspace" title="Grievance categories" description="Use clear, department-specific categories to make citizen submissions easier to route and report on." /><section className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><form onSubmit={submit} className="surface h-fit p-6"><p className="micro-label">Add category</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.04em]">Define a service topic</h2><select value={departmentId} onChange={event => setDepartmentId(event.target.value)} className="mt-6 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Choose department</option>{departments.data?.filter(item => item.status === "active").map(department => <option key={department.id} value={department.id}>{department.name}</option>)}</select><Input value={name} onChange={event => setName(event.target.value)} className="mt-3" placeholder="e.g. Road maintenance" /><Textarea value={description} onChange={event => setDescription(event.target.value)} className="mt-3 min-h-24" placeholder="Brief category guidance" /><MutationAlert message={create.error?.message || setStatus.error?.message} /><Button disabled={create.isPending || !departmentId || name.trim().length < 3} className="mt-4 rounded-xl bg-[#121413] text-white hover:bg-[#303431]"><Plus className="mr-2 h-4 w-4" />Add category</Button></form><div className="grid gap-3 sm:grid-cols-2">{categories.isLoading ? <div className="h-40 animate-pulse rounded-[24px] bg-white" /> : categories.data?.length ? categories.data.map(item => <article key={item.category.id} className="surface p-6"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f9e2e6] text-[#aa6071]"><Tags className="h-4 w-4" /></span><Button size="sm" variant="outline" onClick={() => setStatus.mutate({ categoryId: item.category.id, status: item.category.status === "active" ? "inactive" : "active" })} className="rounded-lg text-xs">{item.category.status === "active" ? "Deactivate" : "Activate"}</Button></div><p className="mt-5 text-xs font-semibold tracking-[0.08em] text-slate-400">{item.department.name}</p><h3 className="mt-1 font-semibold tracking-[-0.03em]">{item.category.name}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{item.category.description || "No description provided."}</p><p className="mt-5 text-xs font-semibold capitalize text-slate-400">{pretty(item.category.status)}</p></article>) : <div className="sm:col-span-2"><EmptyNotice title="No categories yet">Create a department, then define the topics citizens can choose from.</EmptyNotice></div>}</div></section></div>;
}
