import { useAuth } from "@/_core/hooks/useAuth";
import { CaseTitle, EmptyNotice, MetricCard, PageHeader, StatusBadge } from "@/components/CivicPrimitives";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ClipboardList, Clock3, FilePlus2 } from "lucide-react";
import { Link } from "wouter";

export default function CitizenDashboard() {
  const { user } = useAuth();
  const dashboard = trpc.citizen.dashboard.useQuery(undefined, { enabled: user?.role === "user" });
  const data = dashboard.data;
  if (user?.role && user.role !== "user") return <EmptyNotice title="This is not your workspace">Use the navigation for your assigned role.</EmptyNotice>;
  return <div className="space-y-9"><PageHeader eyebrow="Citizen workspace" title={`Welcome${user?.name ? `, ${user.name.split(" ")[0]}` : ""}.`} description="Keep track of your submitted grievances and return to any case when you need to add feedback or review an update." action={<Link href="/grievances/new"><Button className="rounded-xl bg-[#121413] text-white hover:bg-[#303431]"><FilePlus2 className="mr-2 h-4 w-4" />Submit grievance</Button></Link>} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="All cases" value={data?.total ?? 0} hint="Submitted by you" tone="ink" icon={<ClipboardList className="h-5 w-5" />} /><MetricCard label="In progress" value={data?.counts.in_progress ?? 0} hint="Under active handling" tone="blue" icon={<Clock3 className="h-5 w-5" />} /><MetricCard label="Resolved" value={data?.counts.resolved ?? 0} hint="Awaiting your review" tone="lime" icon={<CheckCircle2 className="h-5 w-5" />} /><MetricCard label="Awaiting action" value={(data?.counts.submitted ?? 0) + (data?.counts.acknowledged ?? 0) + (data?.counts.assigned ?? 0)} hint="Being routed or reviewed" tone="pink" icon={<ArrowRight className="h-5 w-5" />} /></section><section className="surface overflow-hidden"><div className="flex items-center justify-between px-6 py-5"><div><p className="micro-label">Recent activity</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.04em]">Your grievances</h2></div><Link href="/grievances" className="text-xs font-semibold text-slate-600 underline decoration-slate-300 underline-offset-4">View all</Link></div>{dashboard.isLoading ? <div className="px-6 pb-7"><div className="h-24 animate-pulse rounded-2xl bg-slate-50" /></div> : data?.recent.length ? <div className="divide-y divide-slate-100">{data.recent.map(item => <Link key={item.grievance.id} href={`/grievances/${item.grievance.id}`} className="flex flex-col gap-4 px-6 py-5 transition hover:bg-[#fafcfc] sm:flex-row sm:items-center sm:justify-between"><CaseTitle trackingNumber={item.grievance.trackingNumber} title={item.grievance.title} location={item.grievance.location} /><div className="flex items-center justify-between gap-6 sm:justify-end"><span className="text-xs text-slate-400">Updated {new Date(item.grievance.updatedAt).toLocaleDateString()}</span><StatusBadge status={item.grievance.status} /></div></Link>)}</div> : <div className="px-6 pb-7"><EmptyNotice title="No grievances yet">When something needs attention, you can submit a grievance in just a few minutes.</EmptyNotice></div>}</section></div>;
}
