import { CivicMark, StatusBadge, TextLink } from "@/components/CivicPrimitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowDown, ArrowRight, Check, CircleHelp, Clock3, FileSearch, Menu, Moon, MoveRight, ShieldCheck, Sparkles, Sun, X } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";

const process = [
  ["01", "Tell us what happened", "Share the issue, location, and any supporting evidence in one clear form."],
  ["02", "We route it responsibly", "The relevant department reviews the case and assigns an accountable officer."],
  ["03", "Follow every update", "Use your tracking ID to see each step from receipt through resolution."],
];

export default function Home() {
  const [, setLocation] = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  const { theme, toggleTheme } = useTheme();
  const [trackingNumber, setTrackingNumber] = useState("");
  const lookup = trpc.public.lookup.useQuery({ trackingNumber: trackingNumber.trim().toUpperCase() }, { enabled: false, retry: false });
  const submitLookup = async (event: FormEvent) => {
    event.preventDefault();
    if (!trackingNumber.trim()) return;
    const result = await lookup.refetch();
    if (result.data) setLocation(`/track/${result.data.trackingNumber}`);
  };
  return (
    <div className="min-h-screen overflow-hidden bg-[#f5f7f8] text-[#121413]">
      <header className="relative z-30 mx-auto flex max-w-[1360px] items-center justify-between px-5 py-5 sm:px-8"><CivicMark /><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#how-it-works" className="transition hover:text-black">How it works</a><a href="#support" className="transition hover:text-black">Service standards</a><Link href="/track" className="transition hover:text-black">Track a case</Link></nav><div className="hidden items-center gap-3 md:flex"><Link href="/staff/login"><Button variant="ghost" className="rounded-xl font-semibold">Staff sign in</Button></Link><Link href="/cases/new"><Button className="rounded-xl bg-[#121413] px-5 text-white hover:bg-[#303431]">Submit a grievance <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div><button onClick={() => setMenuOpen(value => !value)} className="grid h-10 w-10 place-items-center rounded-xl bg-white md:hidden" aria-label="Toggle navigation">{menuOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button><button type="button" onClick={toggleTheme} className="theme-toggle mr-2 grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm md:mr-0" aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} mode`} title={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}>{theme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button></header>
      {menuOpen ? <div className="absolute inset-x-4 top-[76px] z-20 rounded-2xl bg-white p-4 shadow-xl md:hidden"><nav className="flex flex-col gap-1"><a onClick={() => setMenuOpen(false)} href="#how-it-works" className="rounded-xl px-4 py-3 text-sm font-semibold">How it works</a><Link onClick={() => setMenuOpen(false)} href="/track" className="rounded-xl px-4 py-3 text-sm font-semibold">Track a case</Link><Link onClick={() => setMenuOpen(false)} href="/staff/login" className="mt-2 rounded-xl bg-[#121413] px-4 py-3 text-center text-sm font-semibold text-white">Staff sign in</Link></nav></div> : null}

      <main>
        <section className="relative mx-auto grid max-w-[1360px] gap-10 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[1.12fr_0.88fr] lg:items-center lg:pb-28 lg:pt-24">
          <div className="relative z-10 max-w-3xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/80 px-3 py-1.5 text-xs font-medium text-slate-600"><span className="h-1.5 w-1.5 rounded-full bg-[#5394c9]" />A clearer route to resolution</div><h1 className="text-balance text-[clamp(3rem,7vw,6.5rem)] font-semibold leading-[0.93] tracking-[-0.075em]">Your voice belongs <span className="relative whitespace-nowrap">in the process.<i className="absolute -bottom-3 left-2 h-3 w-[92%] rounded-full bg-[#f4bec9]/70" /></span></h1><p className="mt-9 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">Submit a civic concern, follow its progress, and manage service work without accounts, passwords, or complicated steps.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/cases/new"><Button size="lg" className="w-full rounded-xl bg-[#121413] px-6 text-white hover:bg-[#303431] sm:w-auto">Start a grievance <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/track"><Button size="lg" variant="outline" className="w-full rounded-xl border-slate-300 bg-white px-6 sm:w-auto">Track a submitted case</Button></Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs text-slate-500"><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#1e7b5e]" />No account required</span><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#1e7b5e]" />Clear status updates</span><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#1e7b5e]" />Open service access</span></div></div>
          <div className="relative mx-auto w-full max-w-[500px] lg:mr-0"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-[#dceefa]" /><div className="absolute -bottom-14 -left-12 h-40 w-40 rotate-12 rounded-[36px] bg-[#f9dfe4]" /><div className="relative overflow-hidden rounded-[32px] border border-white/70 bg-white p-5 shadow-[0_30px_70px_rgba(55,73,84,0.12)] sm:p-7"><div className="flex items-start justify-between"><div><p className="micro-label">Open case service</p><p className="mt-2 text-xl font-semibold tracking-[-0.05em]">Status at a glance</p></div><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#eaf1d8]"><ShieldCheck className="h-5 w-5 text-[#526641]" /></span></div><div className="mt-8 rounded-2xl bg-[#f5f7f8] p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold tracking-[0.08em] text-slate-400">GRV-2026-00017</p><StatusBadge status="in_progress" /></div><p className="mt-5 text-lg font-semibold tracking-[-0.04em]">Streetlight outage near Maple Square</p><p className="mt-2 text-sm leading-6 text-slate-500">The service team is arranging an inspection and recording each step in the open case record.</p><div className="mt-6 flex items-center gap-2 text-xs font-medium text-slate-500"><Clock3 className="h-3.5 w-3.5" />Updated today, 09:45</div></div><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-[#dfeffc] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#4e84b1]">Stage</p><p className="mt-1 text-sm font-semibold">03 / 05</p></div><div className="rounded-2xl bg-[#f9e2e6] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#a76676]">Priority</p><p className="mt-1 text-sm font-semibold">Medium</p></div><div className="rounded-2xl bg-[#eaf1d8] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#70855f]">Case note</p><p className="mt-1 text-sm font-semibold">New</p></div></div></div><div className="absolute -right-4 top-1/2 grid h-16 w-16 rotate-12 place-items-center rounded-2xl bg-[#121413] text-white shadow-xl"><Sparkles className="h-5 w-5" /></div></div>
        </section>

        <section className="border-y border-slate-200 bg-white" id="support"><div className="mx-auto grid max-w-[1360px] gap-8 px-5 py-8 sm:grid-cols-3 sm:px-8"><div className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#dfeffc]"><FileSearch className="h-4 w-4 text-[#245d8d]" /></span><div><p className="text-sm font-semibold">One tracking ID</p><p className="mt-0.5 text-xs text-slate-500">Find your case whenever you need.</p></div></div><div className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f9e2e6]"><Clock3 className="h-4 w-4 text-[#aa6071]" /></span><div><p className="text-sm font-semibold">Updates you can follow</p><p className="mt-0.5 text-xs text-slate-500">See every meaningful workflow step.</p></div></div><div className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf1d8]"><ShieldCheck className="h-4 w-4 text-[#5a6d4c]" /></span><div><p className="text-sm font-semibold">Open to use</p><p className="mt-0.5 text-xs text-slate-500">No account or password is required.</p></div></div></div></section>

        <section className="mx-auto max-w-[1360px] px-5 py-20 sm:px-8 lg:py-28" id="how-it-works"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="micro-label">How it works</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.065em] sm:text-5xl">Built to make each next step visible.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-500">CivicResolve gives every visitor a calm, human path from a reported issue to a documented outcome.</p><TextLink href="/cases/new"><span>Submit a grievance</span></TextLink></div><div className="grid gap-px overflow-hidden rounded-[28px] bg-slate-200 sm:grid-cols-3">{process.map(([number, title, copy], index) => <article key={number} className={`min-h-[235px] bg-white p-6 ${index === 1 ? "sm:bg-[#e7f1fb]" : ""}`}><p className="text-xs font-semibold tracking-[0.12em] text-slate-400">{number}</p><h3 className="mt-12 text-lg font-semibold tracking-[-0.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div></div></section>

        <section className="mx-auto max-w-[1360px] px-5 pb-20 sm:px-8 lg:pb-28"><div className="relative overflow-hidden rounded-[32px] bg-[#1b1e1c] px-6 py-10 text-white sm:px-12 sm:py-14"><div className="absolute right-[-80px] top-[-110px] h-72 w-72 rounded-full bg-[#5e91bd] opacity-80" /><div className="absolute bottom-[-120px] right-[120px] h-60 w-60 rounded-[48px] bg-[#ed9ead] opacity-65" /><div className="relative grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><p className="micro-label text-slate-400">Already submitted?</p><h2 className="mt-3 max-w-md text-3xl font-semibold tracking-[-0.055em] sm:text-4xl">A status update is only a tracking number away.</h2><p className="mt-4 max-w-md text-sm leading-6 text-slate-300">Enter the grievance ID from your acknowledgement to view the current public status.</p></div><form onSubmit={submitLookup} className="rounded-2xl bg-white/10 p-2 backdrop-blur"><label className="sr-only" htmlFor="homepage-track">Grievance tracking number</label><div className="flex flex-col gap-2 sm:flex-row"><Input id="homepage-track" value={trackingNumber} onChange={event => setTrackingNumber(event.target.value)} placeholder="e.g. GRV-2026-00001" className="h-12 border-white/10 bg-white text-[#121413] placeholder:text-slate-400 focus-visible:ring-[#9ccbf4]" /><Button type="submit" disabled={lookup.isFetching || !trackingNumber.trim()} className="h-12 rounded-xl bg-[#dfeffc] px-5 text-[#121413] hover:bg-white">{lookup.isFetching ? "Looking up…" : "Track case"}<MoveRight className="ml-2 h-4 w-4" /></Button></div>{lookup.error ? <p className="px-3 pb-1 pt-2 text-xs text-[#ffc9d3]">{lookup.error.message}</p> : null}</form></div></div></section>
      </main>
      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-[1360px] flex-col gap-5 px-5 py-8 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><CivicMark /><p>For a more responsive, accountable civic service.</p><Link href="/track" className="font-semibold text-slate-700">Track a case</Link></div></footer>
    </div>
  );
}
