import { useAuth } from "@/_core/hooks/useAuth";
import { CaseTitle, EmptyNotice, MetricCard, PageHeader, StatusBadge } from "@/components/CivicPrimitives";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ClipboardCheck, Flame, Hourglass } from "lucide-react";
import { Link } from "wouter";

export default function OfficerDashboard() {
  const { user } = useAuth();
  const queue = trpc.officer.queue.useQuery(undefined, { enabled: user?.role === "officer" });
  const counts = (queue.data || []).reduce<Record<string, number>>((memo, item) => { memo[item.grievance.status] = (memo[item.grievance.status] || 0) + 1; return memo; }, {});
  if (user?.role && user.role !== "officer") return <EmptyNotice title="This is not your workspace">Use the navigation for your assigned role.</EmptyNotice>;
  return <div className="space-y-9"><PageHeader eyebrow="Officer workspace" title="Your workload, clearly prioritized." description="Review your assigned cases, record each meaningful action, and keep citizens informed as work moves forward." action={<Link href="/officer/grievances"><Button className="rounded-xl bg-[#121413] text-white hover:bg-[#303431]">Open assigned queue <ArrowRight className="ml-2 h-4 w-4" /></Button></Link>} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Assigned" value={queue.data?.length ?? 0} hint="Cases in your queue" tone="ink" icon={<ClipboardCheck className="h-5 w-5" />} /><MetricCard label="In progress" value={counts.in_progress ?? 0} hint="Current active cases" tone="blue" icon={<Hourglass className="h-5 w-5" />} /><MetricCard label="Escalated" value={counts.escalated ?? 0} hint="Needs extra attention" tone="pink" icon={<Flame className="h-5 w-5" />} /><MetricCard label="Resolved" value={counts.resolved ?? 0} hint="Awaiting closure" tone="lime" icon={<CheckCircle2 className="h-5 w-5" />} /></section><section className="surface overflow-hidden"><div className="flex items-center justify-between px-6 py-5"><div><p className="micro-label">Focus queue</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.04em]">Recently updated assignments</h2></div><Link href="/officer/grievances" className="text-xs font-semibold text-slate-600 underline decoration-slate-300 underline-offset-4">See queue</Link></div>{queue.isLoading ? <div className="p-6"><div className="h-20 animate-pulse rounded-2xl bg-slate-50" /></div> : queue.data?.length ? <div className="divide-y divide-slate-100">{queue.data.slice(0, 5).map(item => <Link key={item.grievance.id} href={`/officer/grievances/${item.grievance.id}`} className="flex flex-col gap-4 px-6 py-5 transition hover:bg-[#fafcfc] sm:flex-row sm:items-center sm:justify-between"><CaseTitle trackingNumber={item.grievance.trackingNumber} title={item.grievance.title} location={item.grievance.location} /><div className="flex items-center gap-4"><span className="text-xs text-slate-400">Updated {new Date(item.grievance.updatedAt).toLocaleDateString()}</span><StatusBadge status={item.grievance.status} /></div></Link>)}</div> : <div className="p-6"><EmptyNotice title="Your queue is clear">When an administrator assigns a case to you, it will appear here with its service context and next step.</EmptyNotice></div>}</section></div>;
}
