import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyNotice, PageHeader } from "@/components/CivicPrimitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { AtSign, BadgeCheck, Save, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

export default function Profile() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); useEffect(() => { setName(user?.name || ""); setEmail(user?.email || ""); }, [user?.name, user?.email]); const update = trpc.profile.update.useMutation({ onSuccess: () => { utils.auth.me.invalidate(); toast.success("Profile saved"); }, onError: error => toast.error(error.message) });
  if (user?.role && user.role !== "user") return <EmptyNotice title="This is not your profile workspace">Your role-specific workspace contains the service tools available to you.</EmptyNotice>;
  const submit = (event: FormEvent) => { event.preventDefault(); update.mutate({ name: name.trim() || undefined, email: email.trim() || undefined }); };
  return <div className="mx-auto max-w-4xl space-y-8"><PageHeader eyebrow="Citizen workspace" title="My profile" description="Review the contact details connected to your grievance records and update the information you want service teams to use." /><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="surface bg-[#e7f1fb] p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#245d8d]"><UserRound className="h-5 w-5" /></span><h2 className="mt-7 text-2xl font-semibold tracking-[-0.05em]">Your private service profile</h2><p className="mt-3 text-sm leading-6 text-slate-600">These details remain associated with cases you submit. Authorized staff see them only when handling your grievance.</p><div className="mt-8 flex items-center gap-2 text-xs font-semibold text-[#477ca7]"><BadgeCheck className="h-4 w-4" />Signed in with managed identity</div></section><form onSubmit={submit} className="surface p-7"><p className="micro-label">Account details</p><div className="mt-6 space-y-5"><div><Label htmlFor="profile-name">Name</Label><div className="relative mt-2"><UserRound className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input id="profile-name" value={name} onChange={event => setName(event.target.value)} className="pl-9" placeholder="Your name" /></div></div><div><Label htmlFor="profile-email">Email address</Label><div className="relative mt-2"><AtSign className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input id="profile-email" type="email" value={email} onChange={event => setEmail(event.target.value)} className="pl-9" placeholder="name@example.org" /></div></div><div className="rounded-xl bg-[#f5f7f8] p-4 text-xs leading-5 text-slate-500">Your sign-in security is managed through the portal authentication service. Contact details here support grievance communication only.</div><Button type="submit" disabled={update.isPending || (!name.trim() && !email.trim())} className="rounded-xl bg-[#121413] text-white hover:bg-[#303431]">{update.isPending ? "Saving…" : <><Save className="mr-2 h-4 w-4" />Save profile</>}</Button></div></form></div></div>;
}
